---
deployment:
    tasks:
    - export DEPLOYPATH=/home/qcomptuing/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp coming-soon.html $DEPLOYPATH
    - /bin/cp meet-your-tc.html $DEPLOYPATH
    - /bin/cp faq.html $DEPLOYPATH
    - /bin/cp registration.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
